"""add five-day learning loop tables

Revision ID: 1c1e826a3e7d
Revises: d8a3f6c1b2e7
Create Date: 2026-08-20 07:24:05.468024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1e826a3e7d'
down_revision = 'd8a3f6c1b2e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('concept_lesson_id', sa.String(), nullable=True),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('pacing_day', sa.Integer(), nullable=True),
    sa.Column('evaluation_mode', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_assignment_code', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_lesson_id'], ['concept_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'concept_lesson_id', 'activity_type', 'source_assignment_code', name='uq_learning_activity_slot')
    )
    op.create_index(op.f('ix_learning_activities_chapter_id'), 'learning_activities', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_learning_activities_concept_lesson_id'), 'learning_activities', ['concept_lesson_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('learning_activity_id', sa.String(), nullable=False),
    sa.Column('assigned_by_user_id', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('source_prerequisite_link_id', sa.String(), nullable=True),
    sa.Column('pacing_mode', sa.String(length=20), nullable=False),
    sa.Column('available_from', sa.String(length=30), nullable=True),
    sa.Column('due_date', sa.String(length=30), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['learning_activity_id'], ['learning_activities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_prerequisite_link_id'], ['prerequisite_links.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_learning_activity_id'), 'assignments', ['learning_activity_id'], unique=False)
    op.create_index(op.f('ix_assignments_school_id'), 'assignments', ['school_id'], unique=False)
    op.create_table('learning_activity_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learning_activity_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learning_activity_id'], ['learning_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learning_activity_id', 'question_id', name='uq_activity_question')
    )
    op.create_index(op.f('ix_learning_activity_questions_learning_activity_id'), 'learning_activity_questions', ['learning_activity_id'], unique=False)
    op.create_index(op.f('ix_learning_activity_questions_question_id'), 'learning_activity_questions', ['question_id'], unique=False)
    op.create_table('assignment_targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='uq_assignment_target')
    )
    op.create_index(op.f('ix_assignment_targets_assignment_id'), 'assignment_targets', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_targets_student_id'), 'assignment_targets', ['student_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assignment_target_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_target_id'], ['assignment_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_target_id', 'attempt_number', name='uq_attempt_number')
    )
    op.create_index(op.f('ix_attempts_assignment_target_id'), 'attempts', ['assignment_target_id'], unique=False)
    op.create_table('attempt_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('auto_score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_answer')
    )
    op.create_index(op.f('ix_attempt_answers_attempt_id'), 'attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_answers_question_id'), 'attempt_answers', ['question_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('auto_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_attempt_id'), 'evaluations', ['attempt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_attempt_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_attempt_answers_question_id'), table_name='attempt_answers')
    op.drop_index(op.f('ix_attempt_answers_attempt_id'), table_name='attempt_answers')
    op.drop_table('attempt_answers')
    op.drop_index(op.f('ix_attempts_assignment_target_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_assignment_targets_student_id'), table_name='assignment_targets')
    op.drop_index(op.f('ix_assignment_targets_assignment_id'), table_name='assignment_targets')
    op.drop_table('assignment_targets')
    op.drop_index(op.f('ix_learning_activity_questions_question_id'), table_name='learning_activity_questions')
    op.drop_index(op.f('ix_learning_activity_questions_learning_activity_id'), table_name='learning_activity_questions')
    op.drop_table('learning_activity_questions')
    op.drop_index(op.f('ix_assignments_school_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_learning_activity_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_learning_activities_concept_lesson_id'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_chapter_id'), table_name='learning_activities')
    op.drop_table('learning_activities')
    # ### end Alembic commands ###
