"""add curriculum and question bank tables

Revision ID: 79da5c54ff2a
Revises: 0d1fbedfd27b
Create Date: 2026-08-17 19:11:21.000299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79da5c54ff2a'
down_revision = '0d1fbedfd27b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('class_levels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subject_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('board_courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=False),
    sa.Column('class_level_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_level_id'], ['class_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'class_level_id', 'code', name='uq_board_course')
    )
    op.create_index(op.f('ix_board_courses_board_id'), 'board_courses', ['board_id'], unique=False)
    op.create_index(op.f('ix_board_courses_class_level_id'), 'board_courses', ['class_level_id'], unique=False)
    op.create_table('curriculum_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.String(length=30), nullable=True),
    sa.Column('effective_to', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'code', name='uq_curriculum_version_board_code')
    )
    op.create_index(op.f('ix_curriculum_versions_board_id'), 'curriculum_versions', ['board_id'], unique=False)
    op.create_table('disciplines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('subject_group_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subject_group_id'], ['subject_groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_disciplines_subject_group_id'), 'disciplines', ['subject_group_id'], unique=False)
    op.create_table('course_discipline_maps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board_course_id', sa.String(), nullable=False),
    sa.Column('discipline_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_course_id'], ['board_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_course_id', 'discipline_id', name='uq_course_discipline')
    )
    op.create_index(op.f('ix_course_discipline_maps_board_course_id'), 'course_discipline_maps', ['board_course_id'], unique=False)
    op.create_index(op.f('ix_course_discipline_maps_discipline_id'), 'course_discipline_maps', ['discipline_id'], unique=False)
    op.create_table('terms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('curriculum_version_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_version_id', 'code', name='uq_term_version_code')
    )
    op.create_index(op.f('ix_terms_curriculum_version_id'), 'terms', ['curriculum_version_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('discipline_id', sa.String(), nullable=False),
    sa.Column('term_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discipline_id', 'code', name='uq_chapter_discipline_code')
    )
    op.create_index(op.f('ix_chapters_discipline_id'), 'chapters', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_chapters_term_id'), 'chapters', ['term_id'], unique=False)
    op.create_table('concept_lessons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('learning_outcome', sa.Text(), nullable=True),
    sa.Column('prerequisite_note', sa.Text(), nullable=True),
    sa.Column('priority_misconception', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'code', name='uq_concept_lesson_chapter_code')
    )
    op.create_index(op.f('ix_concept_lessons_chapter_id'), 'concept_lessons', ['chapter_id'], unique=False)
    op.create_table('school_curriculum_maps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('board_course_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('teacher_id', sa.String(), nullable=True),
    sa.Column('planned_start_date', sa.String(length=30), nullable=True),
    sa.Column('planned_end_date', sa.String(length=30), nullable=True),
    sa.Column('textbook_reference', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['board_course_id'], ['board_courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'chapter_id', 'class_name', 'section', name='uq_school_curriculum_map_slot')
    )
    op.create_index(op.f('ix_school_curriculum_maps_board_course_id'), 'school_curriculum_maps', ['board_course_id'], unique=False)
    op.create_index(op.f('ix_school_curriculum_maps_chapter_id'), 'school_curriculum_maps', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_school_curriculum_maps_school_id'), 'school_curriculum_maps', ['school_id'], unique=False)
    op.create_index(op.f('ix_school_curriculum_maps_teacher_id'), 'school_curriculum_maps', ['teacher_id'], unique=False)
    op.create_table('prerequisite_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('concept_lesson_id', sa.String(), nullable=False),
    sa.Column('prerequisite_concept_lesson_id', sa.String(), nullable=False),
    sa.Column('minimum_mastery', sa.Integer(), nullable=True),
    sa.Column('rescue_activity_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['concept_lesson_id'], ['concept_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_concept_lesson_id'], ['concept_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_lesson_id', 'prerequisite_concept_lesson_id', name='uq_prerequisite_edge')
    )
    op.create_index(op.f('ix_prerequisite_links_concept_lesson_id'), 'prerequisite_links', ['concept_lesson_id'], unique=False)
    op.create_index(op.f('ix_prerequisite_links_prerequisite_concept_lesson_id'), 'prerequisite_links', ['prerequisite_concept_lesson_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('concept_lesson_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('assignment_code', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('competency', sa.String(length=150), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=True),
    sa.Column('option_b', sa.Text(), nullable=True),
    sa.Column('option_c', sa.Text(), nullable=True),
    sa.Column('option_d', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('accepted_variants', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('misconception_tag', sa.Text(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.Column('auto_gradable', sa.Boolean(), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), nullable=False),
    sa.Column('response_format', sa.String(length=50), nullable=True),
    sa.Column('media_required', sa.String(length=100), nullable=True),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_alignment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['concept_lesson_id'], ['concept_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_question_code')
    )
    op.create_index(op.f('ix_questions_concept_lesson_id'), 'questions', ['concept_lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_concept_lesson_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_prerequisite_links_prerequisite_concept_lesson_id'), table_name='prerequisite_links')
    op.drop_index(op.f('ix_prerequisite_links_concept_lesson_id'), table_name='prerequisite_links')
    op.drop_table('prerequisite_links')
    op.drop_index(op.f('ix_school_curriculum_maps_teacher_id'), table_name='school_curriculum_maps')
    op.drop_index(op.f('ix_school_curriculum_maps_school_id'), table_name='school_curriculum_maps')
    op.drop_index(op.f('ix_school_curriculum_maps_chapter_id'), table_name='school_curriculum_maps')
    op.drop_index(op.f('ix_school_curriculum_maps_board_course_id'), table_name='school_curriculum_maps')
    op.drop_table('school_curriculum_maps')
    op.drop_index(op.f('ix_concept_lessons_chapter_id'), table_name='concept_lessons')
    op.drop_table('concept_lessons')
    op.drop_index(op.f('ix_chapters_term_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_discipline_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_terms_curriculum_version_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_course_discipline_maps_discipline_id'), table_name='course_discipline_maps')
    op.drop_index(op.f('ix_course_discipline_maps_board_course_id'), table_name='course_discipline_maps')
    op.drop_table('course_discipline_maps')
    op.drop_index(op.f('ix_disciplines_subject_group_id'), table_name='disciplines')
    op.drop_table('disciplines')
    op.drop_index(op.f('ix_curriculum_versions_board_id'), table_name='curriculum_versions')
    op.drop_table('curriculum_versions')
    op.drop_index(op.f('ix_board_courses_class_level_id'), table_name='board_courses')
    op.drop_index(op.f('ix_board_courses_board_id'), table_name='board_courses')
    op.drop_table('board_courses')
    op.drop_table('subject_groups')
    op.drop_table('class_levels')
    op.drop_table('boards')
    # ### end Alembic commands ###
