"""initial schema: schools, users, students, teachers, audit_logs

Revision ID: 8ab65bd640d3
Revises: 
Create Date: 2026-08-17 15:07:11.699170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab65bd640d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('board', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('totp_pending_secret', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_backup_codes_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('teachers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('teacher_code', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('subject_specialization', sa.String(length=150), nullable=True),
    sa.Column('qualification', sa.String(length=150), nullable=True),
    sa.Column('joining_date', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('signature_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('student_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_id', sa.String(length=80), nullable=True),
    sa.Column('teacher_id', sa.String(), nullable=True),
    sa.Column('admission_date', sa.String(length=30), nullable=True),
    sa.Column('dob', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('blood_group', sa.String(length=30), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('signature_url', sa.Text(), nullable=True),
    sa.Column('present_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('father_name', sa.String(length=150), nullable=True),
    sa.Column('father_occupation', sa.String(length=150), nullable=True),
    sa.Column('father_mobile', sa.String(length=30), nullable=True),
    sa.Column('father_email', sa.String(length=150), nullable=True),
    sa.Column('father_whatsapp', sa.String(length=30), nullable=True),
    sa.Column('mother_name', sa.String(length=150), nullable=True),
    sa.Column('mother_occupation', sa.String(length=150), nullable=True),
    sa.Column('mother_mobile', sa.String(length=30), nullable=True),
    sa.Column('mother_email', sa.String(length=150), nullable=True),
    sa.Column('mother_whatsapp', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_id'),
    sa.UniqueConstraint('student_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_index(op.f('ix_students_teacher_id'), 'students', ['teacher_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_student_id'), 'audit_logs', ['student_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_student_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_students_teacher_id'), table_name='students')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_table('users')
    op.drop_table('schools')
    # ### end Alembic commands ###
